export const Model = {
    prop_type: "",
    bedrooms: "",
    baths: "",
    currency: "",
    areaunit: "",
    furnished: "",
    living_room: "",
    balcony: "",
    lift: "",
    parking: "",
    storage: "",
    gym: "",
    cinema: "",
    conference: "",
    swimming_poll: "",
    maid_room: "",
    sports: "",
    maxprice: 100000000,
    minprice: "",
    country: "",
    state: "",
    city: "",
    subcat: "",
    category: "",
};
