const Model = {
    id: 0,
    title: "",
    prop_type: "",
    code: "",
    phone: "",
    address: "",
    price: "",
    currency: "",
    area: "",
    areaunit: "",
    bedrooms: "",
    baths: "",
    description: "",
    furnished: false,
    living_room: false,
    balcony: false,
    lift: false,
    parking: false,
    storage: false,
    gym: false,
    cinema: false,
    conference: false,
    swimming_poll: false,
    maid_room: false,
    sports: false,
    linkurl: "no",
    is_active: false,
    is_reject: false,
    is_publish: false,
    view: 1,
    created_at: "",
    updated_at: null,
    is_deleted: false,
    uid: 0,
    category: 0,
    subcategory: 0,
    country: 0,
    state: 0,
    city: 0,
};

export default Model;
